### ISSUE TITLE
Volumio upgrade not working anymore

### ISSUE THREAD

**Issue by alfieoriginal** [matthuisman/pinn-os#26]
Hello, Volumio version is almost two years old and upgrade process is not working anymore. Could you please check and fix upgrade procedure? Thank you in advance!

**Comment by alfieoriginal** [comment]
Hi again, should I give you more details? Anything you need.

**Comment by matthuisman** [comment]
i dont think i even have a raspberry pi anymore so not sure ill be able to fix this unfortunately :(

**Comment by alfieoriginal** [comment]
Bad news :(    Is there any possibility to help in any way? :)

**Comment by bolek2000** [comment]
Hi guys, I also had the old Volumio running on a PINN install on RPi4 and upgraded from inside the Volumio OS. This also left me with an unbootable partition/VolumioOS. I also would like to test and debug the problem or if possible help upgrading. I'm ok with commandline work, but need a starting point or hint how I could try to test this myself.

**Comment by volumio** [comment]
While I really appreciate the effort here, I shall point out that Volumio has been designed to be run as a standalone OS, and so is the update system. 

Therefore I shall advice to use Volumio as a standalone system, flashing it onto a dedicated SD Card. Using multiboot system WILL have unpredictable consequences and malfunctions, since the development team did not account for the modifications done by the multi-boot system.

**Comment by alfieoriginal** [comment]
Thank you very much for your response. I have enjoyed great Volumio using it in multiboot system thanks to the great work done by matthuisman.
Until a certain update it has worked perfectly and without appreciating differences with respect to a standalone installation. Updates worked really well.
Please, it would be great if you could contribute with some guidelines to make Volumio installable and upgradeable using pinn-os like other great distros.

**Comment by eveningdemons** [comment]
@matthuisman , I know you've already said that you'll probably never get round to fixing this, but it would be greatly appreciated if you could some day. I'm sure @alfieoriginal and myself aren't the only ones using it in a multiboot configuration, inside a media box-style setup. It really defeats the purpose of having enough compute power in one device and not being able to use it to its full potential. And as @alfieoriginal was saying, updates worked fine up until the end of last year.

The main reason seems to be (and I am by no means a coder and don't have the necessary knowledge to understand this further) an expanded partition issue. At some point, one of the updates needed more space, so the partition space was expanded beyond the one you had setup in your custom image.

I'm sure I and other users could provide you with more info, if you'd want to delve deeper.

And even if you never get round to doing that, I'd like to thank you for all your hard work and passion. And for expanding the functionality of tools which have so much more potential than originally thought.

**Comment by arlo-infinity** [comment]
@matthuisman 

Just letting you know that I found that the problem isn't _really_ anything to do with your scripts, but with a change in the size needed for Volumio's boot partition.  Even people with a standalone install of Volumio can't upgrade to v3.569 [Upgrade to v3.569 Not Possible](https://community.volumio.com/t/update-to-v-3-569-not-possible-all-you-need-to-know/63663) because of this change.  That being said, based on my investigations I think if you changed the size of the boot partition in your script to be say 128MB instead of 64MB it should be possible for people to install the v3.198 version you have packaged inside of PINN and upgrade it to the latest version.

@volumio 

FYI. Many people, perhaps a reasonable fraction of your userbase,  have run and continue to run Volumio on multiboot systems without issue.  I agree that multiboot could _potentially_ cause problems and that it isn't your job to cater to multiboot users. However, PINN has handled Volumio easily and without issue up until the v3.569 release including OTA updates. This a big clue that the problem is not with PINN but instead is with the boot partition size on the version of Volumio that the PINN installer supports.   As I detail in the next comment, it is totally possible to manually backup and resize the boot partition in order to enable an OTA update from older versions of Volumio to the latest version, and this actually can be done for standalone installs of Volumio, not just with PINN, if people don't want to lose their old data.

**Comment by arlo-infinity** [comment]
@alfieoriginal @eveningdemons @bolek2000 Hi all.

I had the same problem updating from my install of Volumio on PINN that started as v3.198 and was upgraded to v3.2xx (not sure exactly which but that's not important).

It's possible to do the update but it requires some slightly technical "partition surgery" to get it to work. Volumio has 3 partitions "boot", followed by "volumio", followed by "volumio data" that will show up somewhere in the extended partition that PINN creates depending on where it is located in your OS list in PINN. Note that "boot" may be called "boot1" or "boot2" etc.. when mounted externally again because of the ordering of OS in PINN. Basically, the "boot" partition for Volumio is 64MB but after the update to 3.569 or 3.601 it needs more than 64MB of space, so you need to backup your current "boot" partition and the neighboring "volumio" partition, delete both of them, create a new "boot" partition that is say 128MB in size (64 MB more), create a new "volumio" partition that fills all available space before the "volumio_data" partition (it will be 64MB smaller than before but no big deal as it is quite large), restore your backups of "boot" and "volumio" to the newly sized partitions respectively, and make sure to rename the volume labels back to "boot" or "boot1" or whatever it was originally.

I used the Windows Freeware version of DiskGenius to do this as it is able to backup and restore individual partitions from a drive with many partitions, and is also able to delete and create new partions. If you want to try this and are having trouble with DiskGenius just let me know and I can give some pointers. Advanced users could also do this with GParted under linux using dd to backup/restore your partitions. Actually, both DiskGenius and GParted have "resize partition" and "move partition" features that can be used to move space from one partition to another without creating a backup, but it's more risky and I think the backup-delete-restore method is safer. If you have access to Windows I'd really recommend using DiskGenius as it avoids the command line entirely.

Once you have completed the partition surgery you should be able to boot into Volumio as per normal, the update should work without failing, and you won't lose any of your playlists or other data.   At least it worked for me.

Hope this helps, and let me know if anything is unclear.

**Comment by matthuisman** [comment]
thanks for letting me know. ill try to update Volumio that ships with PINN to latest version and bump up the boot size at same time. Thats usally when i see the change as i check the size of their image etc

**Comment by arlo-infinity** [comment]
> thanks for letting me know. ill try to update Volumio that ships with PINN to latest version and bump up the boot size at same time. Thats usally when i see the change as i check the size of their image etc

Thanks for the rapid response.
That's even better! I'm sure many people will appreciate it and it will eliminate new users of PINN from facing this issue.

**Comment by matthuisman** [comment]
all done with https://github.com/matthuisman/pinn-os/commit/bd595ceb58f9f37a5ca048879388db932d7f89b1

**Comment by eveningdemons** [comment]
@matthuisman , thanks so, so much for finding the time to do this! Everything works perfectly now. Of course, that's also thanks to the creativity of @arlo-infinity . :D

This thread is the definition of the power of community. Thank you to both of you once again for giving us solutions in such a timely manner!

@alfieoriginal & @bolek2000 , the method described by @arlo-infinity worked like a charm and I encountered no issues at all. My SD card PINN multi-boot installs are all intact and I was able to resize the Volumio boot partition. Just a small watch out: you have to downsize another partition where you have enough spare space, and then you can resize the Volumio boot partition with the space you get from that. After that you'll be able to reinstall Volumio in PINN's safe mode. It will install the latest version directly. (3.616).

**Comment by arlo-infinity** [comment]
> This thread is the definition of the power of community. Thank you to both of you once again for giving us solutions in such a timely manner!

No problem! Very happy to share. 

> @alfieoriginal & @bolek2000 , the method described by @arlo-infinity worked like a charm and I encountered no issues at all. My SD card PINN multi-boot installs are all intact and I was able to resize the Volumio boot partition. Just a small watch out: you have to downsize another partition where you have enough spare space, and then you can resize the Volumio boot partition with the space you get from that. After that you'll be able to reinstall Volumio in PINN's safe mode. It will install the latest version directly. (3.616).

Glad everything is working.

Just one small clarification.   If you want to have a fresh install of Volumio 3.616 over your old version while preserving the other OSes on your PINN multiboot setup then you can proceed, after the partition surgery, with a Reinstall of the latest version of Volumio from within the PINN Maintenance screen (as you did).

If you instead want to try and preserve and propagate your settings, network info, Plugins, play history, playlists, radios, favourites, and other userdata to the latest version 3.616 then you should perform all the steps in the partition surgery and afterwords boot back into your older version of Volumio (which now has a 128MB instead of 64MB boot partition but the same files).   Once in Volumio you will then be able to use the Check Updates button inside the Volumio system settings to perform an OTA update to 3.616 preserving your settings/userdata.  

Note that if you subscribe to Volumio Premium then I think the playlists, radios, and favourites (but not other settings/data) are supposed to be backed up to the cloud and restored into a new install. If you are a regular Volumio user then you will need to start over from scratch whenever you do a new install (on PINN or otherwise).
